# -*- coding: utf-8 -*-
"""code_01_collatz_voronoi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dv8Rq2JWAplvyGMsoipQPpVe0acjkwSY
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# Date: April 6, 2026

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from scipy.spatial import Voronoi
from matplotlib.collections import PolyCollection
from matplotlib.colors import LinearSegmentedColormap

# ============================================
# CONFIGURATION
# ============================================
N_DRAW = 1000
N_VORONOI = 3000

# ============================================
# 2-adic Logarithmic Spiral Mapping
# ============================================
def get_spiral_pos(n):
    if n <= 0: return 0.0, 0.0
    r = np.log2(n)
    theta = 2 * np.pi * (r % 1)
    return r * np.cos(theta), r * np.sin(theta)

# ============================================
# Collatz Trajectory Engine (Robust Forward Calc)
# ============================================
def compute_collatz_steps(n_max):
    step = {1: 0}
    parent = {1: None}

    # Extend range slightly to catch high-altitude transient nodes
    for i in range(2, n_max + 1000):
        curr = i
        path = []
        # Prevent infinite loops in unverified systems
        while curr not in step and curr < 10**7:
            path.append(curr)
            nxt = curr // 2 if curr % 2 == 0 else 3 * curr + 1
            parent[curr] = nxt
            curr = nxt

        if curr in step:
            s = step[curr]
            for node in reversed(path):
                s += 1
                step[node] = s
    return step, parent

# ============================================
# Main Visual Synthesis
# ============================================
def create_flawless_mandala():
    print("System Radar: Processing Voronoi Tesselation...")

    # Calculate coordinates and add boundary dummy points
    coords = np.array([get_spiral_pos(i) for i in range(1, N_VORONOI + 1)])
    max_r = np.log2(N_VORONOI)
    theta_dummy = np.linspace(0, 2 * np.pi, 36, endpoint=False)
    dummy = np.column_stack((max_r * 1.3 * np.cos(theta_dummy),
                             max_r * 1.3 * np.sin(theta_dummy)))

    all_coords = np.vstack((coords, dummy))
    vor = Voronoi(all_coords, qhull_options="QJ")

    print("System Radar: Computing Collatz Genealogies...")
    step_dict, parent_map = compute_collatz_steps(N_DRAW)
    valid_steps = [step_dict[i] for i in range(1, N_DRAW + 1) if i in step_dict]
    max_step = max(valid_steps)

    # Figure Setup
    fig, ax = plt.subplots(figsize=(12, 12), facecolor="black")
    ax.set_aspect("equal")
    ax.set_axis_off()

    limit = np.log2(N_DRAW) * 1.1
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)

    # High-Contrast CYM Map (Deep tones for better text legibility)
    deep_colors = ["#008888", "#888800", "#880088"] # Dark Cyan -> Olive -> Deep Magenta
    cmap = LinearSegmentedColormap.from_list("deep_stained_glass", deep_colors)

    # Voronoi PolyCollection Preparation
    polys = []
    for i in range(N_DRAW):
        region = vor.regions[vor.point_region[i]]
        if not region or -1 in region:
            polys.append(np.array([[0, 0]]))
        else:
            polys.append(vor.vertices[region])

    poly_collection = PolyCollection(
        polys,
        facecolors=["black"] * N_DRAW,
        edgecolors="#222222", # Subtle cell boundaries
        linewidths=0.3
    )
    ax.add_collection(poly_collection)

    # Define nodes that form the "Main Trunk" of the system
    trunk_nodes = [2**k for k in range(11)] + [5, 27, 31, 41]

    labels = []
    for n in range(1, N_DRAW + 1):
        x, y = get_spiral_pos(n)

        # Visual hierarchy for numbers
        if n == 27:
            fs, col, z = 14, "#FF77FF", 10 # Highlight the "Monarch"
        elif n in [1, 5, 16]:
            fs, col, z = 11, "#77FFFF", 5  # Critical convergence nodes
        elif n % 2 != 0:
            fs, col, z = 7, "white", 2    # Odd seeds
        else:
            fs, col, z = 6, "#888888", 1    # Even infrastructure

        txt = ax.text(x, y, str(n), color=col, fontsize=fs,
                      ha="center", va="center", alpha=0,
                      fontweight='bold' if n in trunk_nodes else 'normal',
                      zorder=z)
        labels.append(txt)

    # Animation Frame Update
    def update(frame):
        print(f"\rRendering Mandala: Frame {frame}/{max_step}...", end="")
        fc = poly_collection.get_facecolors()

        for i in range(N_DRAW):
            n = i + 1
            if n in step_dict and step_dict[n] <= frame:
                # Color cells only if they are still in the initial state
                if np.all(fc[i][:3] == 0):
                    fc[i] = cmap(step_dict[n] / max_step)
                    # Show labels for odd numbers or trunk nodes upon activation
                    if n % 2 != 0 or n in trunk_nodes:
                        labels[i].set_alpha(1)

        poly_collection.set_facecolors(fc)
        return [poly_collection] + labels

    # Execute Animation
    ani = FuncAnimation(fig, update, frames=range(0, max_step + 1, 2), blit=True)
    ani.save("collatz_stained_glass_1000.gif", writer=PillowWriter(fps=6))

    # Causal Tree Overlay (Final Step)
    print("\nSystem Radar: Weaving Causal Threads...")
    for child in range(1, N_DRAW + 1):
        parent = parent_map.get(child)
        if parent is not None and parent <= N_DRAW:
            x1, y1 = get_spiral_pos(child)
            x2, y2 = get_spiral_pos(parent)
            ax.plot([x1, x2], [y1, y2], color="white", linewidth=0.3, alpha=0.1, zorder=0)

    print("Success: The Mandala is complete.")
    plt.show()

if __name__ == "__main__":
    create_flawless_mandala()

